-- Create pitches table
CREATE TABLE "public"."pitches" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "subject" text not null,
    "body" text not null,
    "contact_id" bigint not null,
    "status" text not null default 'Draft',
    "sales_id" bigint,
    PRIMARY KEY ("id")
);

-- Add foreign key constraints
ALTER TABLE "public"."pitches" ADD CONSTRAINT "pitches_contact_id_fkey" 
    FOREIGN KEY (contact_id) REFERENCES contacts(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."pitches" ADD CONSTRAINT "pitches_sales_id_fkey" 
    FOREIGN KEY (sales_id) REFERENCES sales(id);

-- Enable row level security
ALTER TABLE "public"."pitches" ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Authenticated users can read pitches" 
    ON "public"."pitches" 
    AS PERMISSIVE 
    FOR SELECT 
    TO authenticated 
    USING (true);

CREATE POLICY "Authenticated users can insert pitches" 
    ON "public"."pitches" 
    AS PERMISSIVE 
    FOR INSERT 
    TO authenticated 
    WITH CHECK (true);

CREATE POLICY "Authenticated users can update pitches" 
    ON "public"."pitches" 
    AS PERMISSIVE 
    FOR UPDATE 
    TO authenticated 
    USING (true);

CREATE POLICY "Authenticated users can delete pitches" 
    ON "public"."pitches" 
    AS PERMISSIVE 
    FOR DELETE 
    TO authenticated 
    USING (true);

-- Create a view for pitches with contact information
CREATE VIEW "public"."pitches_with_contacts" AS
SELECT 
    p.id,
    p.created_at,
    p.updated_at,
    p.subject,
    p.body,
    p.status,
    p.contact_id,
    p.sales_id,
    c.first_name AS contact_first_name,
    c.last_name AS contact_last_name,
    c.outlet AS contact_outlet
FROM pitches p
JOIN contacts c ON p.contact_id = c.id;

-- Grant permissions
GRANT ALL ON TABLE "public"."pitches" TO authenticated;
GRANT ALL ON TABLE "public"."pitches" TO service_role;
GRANT ALL ON TABLE "public"."pitches_with_contacts" TO authenticated;
GRANT ALL ON TABLE "public"."pitches_with_contacts" TO service_role;
